baseURL = 'https://example.org/'
locale = 'en-us'
title = "Marina Moya"
theme = 'LoveIt'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "Sobre mí"
    url = "/about/"
    weight = 20

  [[menu.main]]
    identifier = "posts"
    name = "Artículos"
    url = "/posts/"
    weight = 30