baseURL = 'https://example.org/'
locale = 'en-us'
title = "Marina Moya"
theme = 'LoveIt'

[menu]
  [[menu.main]]
    identifier = "sobre-mi"
    name = "Sobre mí"
    url = "/sobre-mi/"
    weight = 20

  [[menu.main]]
    identifier = "salir-de-google"
    name = "Salir de Google"
    url = "/salir-de-google/"
    weight = 20

    [[menu.main]]
    identifier = "producto-digital"
    name = "Desarrollo de Producto"
    url = "/mis-servicios/"
    weight = 30